/*
 * Project Euler Problem 2:
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5,
 * 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed
 * four million, find the sum of the even-valued terms.
 */
#include <iostream>
using std::cout;

int main() {
  unsigned a = 1;
  unsigned b = 1;
  unsigned c = a + b;
  unsigned sum = 0;
  const unsigned MAX = 4000000;
  while (c <= MAX) {
    if (0 == (c & 1)) {
      sum += c;
    }
    a = b;
    b = c;
    c = a + b;
  }
  cout << sum << '\n';
  return 0;
}
